apiVersion: v2
name: aryon
description: A Helm chart for the Aryon microservices (Itemss and Audit services)
type: application
version: v0.3.0
appVersion: "v0.3.0"

dependencies:
  - name: postgresql
    version: 18.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
  - name: grafana
    version: 10.5.12
    repository: https://grafana.github.io/helm-charts
  - name: traefik
    version: 36.0.0
    repository: https://traefik.github.io/charts
    condition: traefik.deployment.enabled
